# Podcast Player API Configuration

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  max_header_bytes: 1048576

# Database configuration
database:
  path: "./data/podcast-player.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Podcast Index API configuration
podcast_index:
  api_key: "${KILLALL_PODCAST_INDEX_API_KEY}"
  api_secret: "${KILLALL_PODCAST_INDEX_API_SECRET}"
  api_url: "https://api.podcastindex.org/api/1.0"
  user_agent: "PodcastPlayerAPI/1.0"
  timeout: 30s

# Storage configuration
storage:
  data_dir: "./data"
  cache_dir: "./cache"
  temp_dir: "/tmp"

# Processing configuration
processing:
  workers: 2
  max_queue_size: 100
  job_timeout: 30m
  ffmpeg_path: "/etc/profiles/per-user/ryan/bin/ffmpeg"    # Your local ffmpeg path
  ffprobe_path: "/etc/profiles/per-user/ryan/bin/ffprobe"  # Your local ffprobe path

# Waveform generation configuration
waveform:
  enabled: true
  resolution: 1000
  sample_rate: 44100
  channels: 1

# Transcription configuration
transcription:
  enabled: true
  whisper_path: "/opt/homebrew/bin/whisper-cpp"
  model_path: "./models/ggml-base.en.bin"
  language: "en"

# Features configuration
features:
  enable_waveform: true
  enable_transcription: true
  enable_streaming: true
  enable_sync: true

# Rate limiting configuration
rate_limiting:
  enabled: true
  cleanup_interval: 1h
  max_age: 24h

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Security configuration
security:
  jwt_secret: "${KILLALL_JWT_SECRET}"
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  api_key_header: "X-API-Key"

# OpenAI configuration (optional, for transcription fallback)
openai:
  api_key: "${KILLALL_OPENAI_API_KEY}"
  model: "whisper-1"
  max_retries: 3
  timeout: 60s

# Whisper API configuration (optional, for cloud transcription)
whisper:
  api_key: "${KILLALL_WHISPER_API_KEY}"
  api_url: "https://api.openai.com/v1/audio/transcriptions"
  model: "whisper-1"