# Podcast Player API Configuration
# Copy this file to config.yaml and update with your settings

# Server configuration
server:
  host: "0.0.0.0"                  # Bind address
  port: 8080                       # HTTP port
  read_timeout: 30s                # Request read timeout
  write_timeout: 30s               # Response write timeout
  shutdown_timeout: 10s            # Graceful shutdown timeout
  max_header_bytes: 1048576        # 1MB max header size

# WebSocket configuration
websocket:
  heartbeat_interval: 30s          # Ping/pong interval
  max_message_size: 10485760       # 10MB max message size
  read_buffer_size: 1024           # Read buffer size
  write_buffer_size: 1024          # Write buffer size
  handshake_timeout: 10s           # Connection handshake timeout
  enable_compression: true         # Enable message compression

# Database configuration
database:
  path: "./data/podcast.db"        # SQLite database path
  max_connections: 10              # Maximum open connections
  max_idle_connections: 5          # Maximum idle connections
  connection_max_lifetime: 30m     # Connection max lifetime
  enable_wal: true                 # Enable WAL mode
  enable_foreign_keys: true        # Enable foreign key constraints
  log_queries: false               # Log SQL queries (debug)

# Audio processing configuration
processing:
  workers: 2                       # Number of worker goroutines
  max_queue_size: 100             # Maximum queue size
  job_timeout: 30m                # Maximum job processing time
  retry_attempts: 3               # Number of retry attempts
  retry_delay: 5s                 # Initial retry delay (exponential backoff)
  
  # FFmpeg settings
  ffmpeg_path: "/usr/local/bin/ffmpeg"     # FFmpeg binary path
  ffprobe_path: "/usr/local/bin/ffprobe"   # FFprobe binary path
  ffmpeg_timeout: 5m                        # FFmpeg operation timeout
  
  # Audiowaveform settings
  audiowaveform_path: "/usr/local/bin/audiowaveform"  # Audiowaveform binary path
  waveform_resolutions:                                # Waveform zoom levels
    - 256                                             # Overview
    - 512                                             # Standard
    - 1024                                            # Detailed
  waveform_bits: 8                                   # Amplitude resolution (8 or 16)

# Podcast Index API configuration
podcast_index:
  api_key: "${PODCAST_INDEX_API_KEY}"      # API key (from environment)
  api_secret: "${PODCAST_INDEX_API_SECRET}" # API secret (from environment)
  base_url: "https://api.podcastindex.org/api/1.0"
  timeout: 10s                              # Request timeout
  retry_attempts: 3                         # Retry attempts
  rate_limit: 10                           # Requests per second
  cache_ttl: 1h                            # Cache time-to-live
  user_agent: "PodcastPlayerAPI/1.0"       # User agent string

# OpenAI Whisper API configuration
whisper:
  api_key: "${OPENAI_API_KEY}"             # OpenAI API key (from environment)
  api_url: "https://api.openai.com/v1/audio/transcriptions"
  model: "whisper-1"                       # Model to use
  language: ""                              # Language hint (empty for auto-detect)
  temperature: 0                            # Sampling temperature (0 for deterministic)
  timeout: 5m                              # Request timeout
  max_file_size: 26214400                  # 25MB max file size
  chunk_duration: 600                       # Chunk duration in seconds (10 minutes)
  cost_per_minute: 0.006                   # Cost tracking
  monthly_quota: 100.0                     # Monthly spending limit in dollars

# Storage configuration
storage:
  temp_dir: "./tmp"                        # Temporary files directory
  cache_dir: "./cache"                     # Cache files directory
  max_temp_age: 24h                        # Maximum age for temp files
  cleanup_interval: 1h                     # Cleanup job interval
  max_cache_size: 10737418240              # 10GB max cache size

# Cache configuration
cache:
  # In-memory cache
  memory:
    default_ttl: 10m                       # Default TTL for cached items
    cleanup_interval: 5m                   # Cleanup interval
    max_entries: 1000                      # Maximum number of entries
  
  # API response cache
  api:
    search_ttl: 1h                         # Search results cache TTL
    podcast_ttl: 24h                       # Podcast info cache TTL
    episode_ttl: 24h                       # Episode info cache TTL

# Streaming configuration
streaming:
  buffer_size: 32768                       # 32KB streaming buffer
  enable_range_requests: true              # Support range requests
  max_concurrent_streams: 10               # Maximum concurrent streams
  bandwidth_limit: 0                       # Bandwidth limit in bytes/sec (0 = unlimited)

# Rate limiting configuration
rate_limiting:
  enabled: true                            # Enable rate limiting
  # Per-endpoint limits (requests per minute)
  endpoints:
    search: 60
    stream: 100
    processing: 10
    websocket: 100
    default: 120

# Security configuration
security:
  enable_cors: true                        # Enable CORS
  cors_origins:                           # Allowed origins
    - "*"                                  # Allow all (change in production)
  cors_methods:                           # Allowed methods
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_headers:                           # Allowed headers
    - "Content-Type"
    - "Authorization"
    - "Range"
  enable_request_id: true                  # Add request ID to requests
  enable_recovery: true                    # Recover from panics

# Logging configuration
logging:
  level: "info"                            # Log level (debug, info, warn, error)
  format: "json"                           # Log format (json, console)
  output: "stdout"                         # Output destination (stdout, file)
  file_path: "./logs/app.log"              # Log file path (if output=file)
  max_size: 100                            # Max log file size in MB
  max_backups: 10                          # Max number of backup files
  max_age: 30                              # Max age in days
  compress: true                           # Compress old log files
  enable_caller: false                     # Include caller information
  enable_stacktrace: true                  # Include stacktrace for errors

# Monitoring configuration
monitoring:
  enabled: false                           # Enable monitoring endpoints
  metrics_path: "/metrics"                 # Prometheus metrics path
  health_path: "/health"                   # Health check path
  pprof_enabled: false                     # Enable pprof endpoints
  pprof_path: "/debug/pprof"               # pprof base path

# Feature flags
features:
  enable_transcription: true               # Enable transcription feature
  enable_waveform: true                   # Enable waveform generation
  enable_tagging: true                    # Enable audio tagging
  enable_caching: true                    # Enable caching
  enable_websocket: true                  # Enable WebSocket support
  maintenance_mode: false                 # Maintenance mode

# Environment-specific overrides
# These can be overridden by environment variables or separate config files
env:
  development:
    logging:
      level: "debug"
    database:
      log_queries: true
    monitoring:
      pprof_enabled: true
  
  production:
    server:
      host: "0.0.0.0"
    logging:
      level: "warn"
      output: "file"
    security:
      cors_origins:
        - "https://yourdomain.com"
    monitoring:
      enabled: true