# Podcast Player API Configuration for Docker

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  max_header_bytes: 1048576

# Database configuration
database:
  path: "/app/data/podcast-player.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Podcast Index API configuration - expects environment variables
podcast_index:
  api_key: "${KILLALL_PODCAST_INDEX_API_KEY}"
  api_secret: "${KILLALL_PODCAST_INDEX_API_SECRET}"
  api_url: "https://api.podcastindex.org/api/1.0"
  user_agent: "PodcastPlayerAPI/1.0"
  timeout: 30s

# Storage configuration - Docker paths
storage:
  data_dir: "/app/data"
  cache_dir: "/app/cache"
  temp_dir: "/tmp"

# Processing configuration - Alpine Linux paths
processing:
  workers: 2
  max_queue_size: 100
  job_timeout: 30m
  ffmpeg_path: "/usr/bin/ffmpeg"
  ffprobe_path: "/usr/bin/ffprobe"

# Waveform generation configuration
waveform:
  enabled: true
  resolution: 1000
  sample_rate: 44100
  channels: 1

# Transcription configuration - for whisper.cpp in Docker
transcription:
  enabled: false  # Disabled by default in Docker unless whisper.cpp is installed
  whisper_path: "/app/bin/whisper"
  model_path: "/app/models/ggml-base.en.bin"
  language: "en"

# Features configuration
features:
  enable_waveform: true
  enable_transcription: false  # Disabled by default in Docker
  enable_streaming: true
  enable_sync: true

# Rate limiting configuration
rate_limiting:
  enabled: true
  cleanup_interval: 1h
  max_age: 24h

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Security configuration
security:
  jwt_secret: "${KILLALL_JWT_SECRET}"
  cors_enabled: true
  cors_origins:
    - "*"  # Allow all origins in Docker (configure as needed)
  api_key_header: "X-API-Key"

# OpenAI configuration (optional, for transcription fallback)
openai:
  api_key: "${KILLALL_OPENAI_API_KEY}"
  model: "whisper-1"
  max_retries: 3
  timeout: 60s

# Whisper API configuration (optional, for cloud transcription)
whisper:
  api_key: "${KILLALL_WHISPER_API_KEY}"
  api_url: "https://api.openai.com/v1/audio/transcriptions"
  model: "whisper-1"