---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: killallplayer-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minipc-nvme
  resources:
    requests:
      storage: 50Gi
