---
apiVersion: v1
kind: Secret
metadata:
  name: killallplayer-secrets
type: Opaque
stringData:
  # Replace these with your actual API keys from .env file
  podcast-index-api-key: "RKP7EHPWA4EXSCTFCBK2"
  podcast-index-api-secret: "MyGH^tCxCV4RMLSe8zG2ac3sJSH58rqSAYAZtzL3"
  # Optional: Add OpenAI API key if needed
  # openai-api-key: "your-openai-api-key"
