---
apiVersion: v1
kind: Service
metadata:
  name: killallplayer-api
  labels:
    app: killallplayer-api
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: killallplayer-api
