name: Run Tests

on:
  push:

# Allow tests and linting to run concurrently but don't cancel running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'
        cache: true
        cache-dependency-path: go.sum
        
    - name: Clear module cache and download fresh dependencies
      run: |
        go clean -modcache
        go mod download
        go mod tidy
        go mod verify
      
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.1
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
    - name: Run unit tests
      run: go test -v ./...


  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'
        cache: true
        cache-dependency-path: go.sum
        
    - name: Clear module cache and download fresh dependencies
      run: |
        go clean -modcache
        go mod download
        go mod tidy
        go mod verify
      
    - name: Run linting
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.1
        args: --timeout=5m